version: '3.8'

services:
  server:
    build:
      context: ./fourier-transform
      dockerfile: ./Dockerfile
    env_file:
      - ./fourier-transform/.env
    ports:
      - 3000:3000
    depends_on:
      - database
      - worker

  worker:
    build:
      context: ./fourier-transform-worker
      dockerfile: ./Dockerfile
    env_file:
      - ./fourier-transform-worker/.env
    ports:
      - 3001:3001
    depends_on:
      - database

  database:
    image: 'mongo'
    container_name: 'mondo-db'
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
    ports:
      - '27017-27019:27017-27019'

  redis:
    image: redis:latest
    expose:
      - 6379
    ports:
      - "6379:6379"
