---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fourier-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fourier-worker
  template:
    metadata:
      labels:
        app: fourier-worker
    spec:
      containers:
        - name: fourier-worker
          image: registry.digitalocean.com/dsd-paas-cr/fourier-worker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: redis-url
                  key: redis_url
